Changes related to B2BL package
Adyen/adyen-apex-api-library pull request #16
Opened 2022-06-06 05:27 UTC by vkuncham

## Summary

## Tested scenarios

**Fixed issue**:

2022-06-13 22:31 UTC, vkuncham commented on force-app/main/default/classes/AuthorisationRequest.cls
> -    public String returnUrl { get; set; }
This class is added in the library for B2B2C package, so we should be fine deleting.

2022-07-20 11:30 UTC, ShubhamVijaivargiya requested changes
We will have to make the AdyenConstants class and its properties namespaceAccessible. Please refer: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_NamespaceAccessible.htm

2022-07-20 19:35 UTC, ShubhamVijaivargiya submitted a review, later dismissed

2022-07-21 11:23 UTC, maassenbas approved these changes

2022-07-25 08:39 UTC, maassenbas approved these changes

2022-07-25 13:16 UTC, ShubhamVijaivargiya approved these changes

2022-07-27 15:06 UTC, merged