SepaDirectDebitDetails and PaymentsResponse classes update
Adyen/adyen-apex-api-library pull request #42
Opened 2024-04-17 12:14 UTC by zenit2001

Describe the changes proposed in this pull request:
- What is the motivation for this change? 
Having a updated class for SepaDirectDebitDetails and having the `paymentMethod` in the `PaymentsResponse` class.
- What existing problem does this pull request solve?
Enables Sepa payments with our B2B offering.

## Tested scenarios
- Sepa Payments
- Card Payments

2024-04-25 07:38 UTC, dcardos approved these changes

2024-05-02 11:26 UTC, ShubhamVijaivargiya requested changes
Can we please fix the indentation issues in PaymentsResponse class?

2024-05-02 12:07 UTC, dcardos approved these changes

2024-05-02 13:57 UTC, ShubhamVijaivargiya approved these changes

2024-05-03 07:50 UTC, merged